"""Mensaje descriptivo

Revision ID: bca5bf2fa0d9
Revises: 
Create Date: 2025-03-19 23:25:11.024956

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'bca5bf2fa0d9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Resultados')
    op.drop_table('Sistemas_Distriucion')
    op.drop_table('Prestadores_Servicios')
    op.drop_table('Puntos_Muestreo')
    op.drop_table('Veredas')
    op.drop_table('Departamentos')
    op.drop_table('Municipios')
    op.drop_index('ix_users_email', table_name='users')
    op.drop_index('ix_users_id', table_name='users')
    op.drop_index('ix_users_name', table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('email', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('password', mysql.VARCHAR(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_users_name', 'users', ['name'], unique=False)
    op.create_index('ix_users_id', 'users', ['id'], unique=False)
    op.create_index('ix_users_email', 'users', ['email'], unique=True)
    op.create_table('Municipios',
    sa.Column('Codigo', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('Nombre', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('Codigo_Departamento', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['Codigo_Departamento'], ['Departamentos.Codigo'], name='Municipios_ibfk_1'),
    sa.PrimaryKeyConstraint('Codigo'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('Departamentos',
    sa.Column('Codigo', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('Nombre', mysql.VARCHAR(length=100), nullable=False),
    sa.PrimaryKeyConstraint('Codigo'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('Veredas',
    sa.Column('Codigo', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('Nombre', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('Codigo_Municipio', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['Codigo_Municipio'], ['Municipios.Codigo'], name='Veredas_ibfk_1'),
    sa.PrimaryKeyConstraint('Codigo'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('Puntos_Muestreo',
    sa.Column('Codigo', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=100), nullable=False),
    sa.Column('Descripcion', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('Direccion', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('Codigo_Vereda', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('Tipo_Punto', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('Clasificacion', mysql.TEXT(charset='utf8mb4', collation='utf8mb4_0900_ai_ci'), nullable=True),
    sa.Column('Tipo_Dispositivo', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('Georreferenciacion', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('Nit_Prestador', mysql.VARCHAR(length=20), nullable=True),
    sa.ForeignKeyConstraint(['Codigo_Vereda'], ['Veredas.Codigo'], name='Puntos_Muestreo_ibfk_1'),
    sa.ForeignKeyConstraint(['Nit_Prestador'], ['Prestadores_Servicios.Nit'], name='Puntos_Muestreo_ibfk_2'),
    sa.PrimaryKeyConstraint('Codigo'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('Prestadores_Servicios',
    sa.Column('Nit', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('Digito_Verificacion', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('Persona_Prestadora', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=500), nullable=True),
    sa.Column('Registrada_SSPD', mysql.VARCHAR(length=10), nullable=True),
    sa.PrimaryKeyConstraint('Nit'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('Sistemas_Distriucion',
    sa.Column('Codigo', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('Tipo_Suministro', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=500), nullable=True),
    sa.Column('Sistema_Distribucion', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=500), nullable=True),
    sa.Column('Suscriptores_Area_Urbana', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('Suscriptores_Area_Rural', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('Total_Poblacion', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('Usuarios_Poblacion_Atendida', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('Total_Poblacion_Atendida', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('Nit_Prestador', mysql.VARCHAR(length=20), nullable=True),
    sa.ForeignKeyConstraint(['Nit_Prestador'], ['Prestadores_Servicios.Nit'], name='Sistemas_Distriucion_ibfk_1'),
    sa.PrimaryKeyConstraint('Codigo'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('Resultados',
    sa.Column('Codigo_Muestra', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('Fecha_Toma', mysql.VARCHAR(length=26), nullable=True),
    sa.Column('Tipo_Agua', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('Codigo_Punto_Muestreo', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=100), nullable=True),
    sa.Column('Resultado_Ph_In_Situ', mysql.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('Diagnostico_Ph_In_Situ', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('Resultado_Color_Aparente_In_Situ', mysql.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('Diagnostico_Color_Aparente_In_Situ', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('Resultado_Turbiedad_In_Situ', mysql.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('Diagnostico_Turbiedad_In_Situ', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('Resultado_Cloro_Residual_Libre_In_Situ', mysql.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('Diagnostico_Cloro_Residual_Libre_In_Situ', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('Resultado_Temperatura_In_Situ', mysql.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('Diagnostico_Temperatura_In_Situ', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('Resultado_Color_Aparente', mysql.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('Diagnostico_Color_Aparente', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('Resultado_Conductividad', mysql.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('Diagnostico_Conductividad', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('Resultado_Ph', mysql.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('Diagnostico_Ph', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('Resultado_Turbiedad', mysql.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('Diagnostico_Turbiedad', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('Resultado_Temperatura', mysql.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('Diagnostico_Temperatura', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('Resultado_Alcalinidad_Total', mysql.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('Diagnostico_Alcalinidad_Total', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('Resultado_Aluminio', mysql.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('Diagnostico_Aluminio', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('Resultado_Cloro_Residual_Libre', mysql.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('Diagnostico_Cloro_Residual_Libre', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('Resultado_Cloruros', mysql.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('Diagnostico_Cloruros', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('Resultado_COT', mysql.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('Diagnostico_COT', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('Resultado_Dureza_Calcica', mysql.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('Diagnostico_Dureza_Calcica', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('Resultado_Dureza_Total', mysql.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('Diagnostico_Dureza_Total', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('Resultado_Fosfatos', mysql.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('Diagnostico_Fosfatos', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('Resultado_Manganeso', mysql.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('Diagnostico_Manganeso', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('Resultado_Nitratos', mysql.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('Diagnostico_Nitratos', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('Resultado_Nitritos', mysql.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('Diagnostico_Nitritos', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('Resultado_Sulfatos', mysql.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('Diagnostico_Sulfatos', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('Resultado_Coliformes_Totales', mysql.DOUBLE(asdecimal=True), nullable=True),
    sa.Column('Diagnostico_Coliformes_Totales', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('Resultado_E_Coli', mysql.DOUBLE(asdecimal=True), nullable=True),
    sa.Column('Diagnostico_E_Coli', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('Resultado_Floruros', mysql.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('Diagnostico_Floruros', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('Resultado_Hierro_Total', mysql.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('Diagnostico_Hierro_Total', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('IRCA_Basico', mysql.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('IRCA', mysql.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('Nivel_Riesgo', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('Observaciones', mysql.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['Codigo_Punto_Muestreo'], ['Puntos_Muestreo.Codigo'], name='Resultados_Puntos_Muestreo_FK'),
    sa.PrimaryKeyConstraint('Codigo_Muestra'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
